name: ESIOS Daily Data Fetch

on:
  schedule:
    - cron: "00 06 * * *"  # Ejecuta cada día a las 12:35 UTC
  workflow_dispatch:       # Permite ejecución manual desde GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TOKEN_ESIOS: ${{ secrets.TOKEN_ESIOS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run precio_mercado.py script
        run: python app/precio_mercado.py


      - name: Upload precio_diario.csv artifact
        uses: actions/upload-artifact@v4
        with:
          name: datos_csv
          path: precio_diario.csv
